# Generated by Django 4.2.7 on 2026-06-05 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0007_jira_issue_link_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Skills 内容(Markdown)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='projects.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_skills', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
            ],
            options={
                'verbose_name': '项目 Skills',
                'verbose_name_plural': '项目 Skills',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to='knowledge/%Y/%m/', verbose_name='文件')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('content_text', models.TextField(blank=True, verbose_name='全文内容')),
                ('chunks', models.JSONField(default=list, verbose_name='段落列表')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('indexed', '已索引'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_docs', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_docs', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '知识库文档',
                'verbose_name_plural': '知识库文档',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE requirement_analysis_knowledgedocument ADD FULLTEXT INDEX idx_content_fulltext (content_text);",
            reverse_sql="ALTER TABLE requirement_analysis_knowledgedocument DROP INDEX idx_content_fulltext;",
        ),
    ]
