# Generated by Django 4.2.7 on 2026-08-03 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0003_visibility_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteBrowserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('service_type', models.CharField(choices=[('selenium_grid', 'Selenium Grid'), ('playwright_remote', 'Playwright Remote'), ('playwright_cdp', 'Playwright CDP'), ('browserstack', 'BrowserStack'), ('saucelabs', 'Sauce Labs')], max_length=30, verbose_name='服务类型')),
                ('url', models.CharField(max_length=500, verbose_name='连接地址')),
                ('capabilities', models.JSONField(blank=True, default=dict, verbose_name='浏览器能力配置')),
                ('auth_config', models.JSONField(blank=True, default=dict, verbose_name='认证配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_browser_services', to='ui_automation.uiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '远程浏览器服务',
                'verbose_name_plural': '远程浏览器服务',
                'db_table': 'ui_remote_browser_services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='remote_browser_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_case_executions', to='ui_automation.remotebrowserservice', verbose_name='远程浏览器服务'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='remote_browser_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='ui_automation.remotebrowserservice', verbose_name='远程浏览器服务'),
        ),
        migrations.AddField(
            model_name='uischeduledtask',
            name='remote_browser_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='ui_automation.remotebrowserservice', verbose_name='远程浏览器服务'),
        ),
    ]
