# Generated by Django 4.2.7 on 2026-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0010_recording_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='case_parameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='用例级参数覆盖'),
        ),
        migrations.AddField(
            model_name='testcasestep',
            name='step_parameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='步骤级参数覆盖'),
        ),
    ]
